esphome:
  name: presence-sensor-street
  friendly_name: Presence sensor street

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
#logger:
#  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "your_key" #укажите ваш ключ

ota:
  - platform: esphome
    password: "your_pass" #укажите ваш пароль

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Presence Sensor street"
    password: "12345678"

i2c:
  sda: GPIO08
  scl: GPIO09
  scan: true
  id: bus_a
  frequency: 400MHz
captive_portal:
web_server: 
  version: 3

mdns:
  disabled: true


output:
  - platform: ledc
    id: led
    pin: 1
    max_power: 0.7

  - platform: ledc
    pin: 10
    id: relay

switch:
  - platform: ld2410
    bluetooth:
      name: "Sensor bluetooth"

light:
  - platform: monochromatic
    id: status_led
    output: led
    name: LED
    internal: True
    default_transition_length: 0s

  - platform: binary
    id: light_switch
    output: relay
    name: "Light"

uart:
  id: uart_ld2410
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  data_bits: 8

ld2410:
  uart_id: uart_ld2410
 # setup_priority: -100


binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      on_state:
        - if:
            condition:
              - lambda: return (id(ambient).state <= id(start_lux).state);
              - light.is_off: light_switch
            then:
              - light.turn_on: status_led
              - delay: 0.1s
              - light.turn_off: status_led
              - delay: 0.1s
              - light.turn_on: status_led
              - delay: 0.1s
              - light.turn_off: status_led
              - light.turn_on: light_switch
            else:
              - light.turn_off: light_switch


    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

#  - platform: gpio
#    pin: GPIO10
#    name: gpio out pin presence
#    device_class: presence

sensor:
  - platform: tsl2561
    name: "Ambient light"
    address: 0x39
    id: ambient
    update_interval: 60s


  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance

  - platform: wifi_signal
    name:  Wi-Fi RSSI

number:
  - platform: ld2410
    timeout:
      name: Timeout
    light_threshold:
      name: Light threshold
      internal: True
    max_move_distance_gate:
      name: Max move distance gate
      internal: True
    max_still_distance_gate:
      name: Max still distance gate
      internal: True
    g0:
      move_threshold:
        name: G0 move threshold
        internal: True
      still_threshold:
        name: G0 still threshold
        internal: True
    g1:
      move_threshold:
        name: G1 move threshold
        internal: True
      still_threshold:
        name: G1 still threshold
        internal: True
    g2:
      move_threshold:
        name: G2 move threshold
        internal: True
      still_threshold:
        name: G2 still threshold
        internal: True
    g3:
      move_threshold:
        name: G3 move threshold
        internal: True
      still_threshold:
        name: G3 still threshold
        internal: True
    g4:
      move_threshold:
        name: G4 move threshold
        internal: True
      still_threshold:
        name: G4 still threshold
        internal: True
    g5:
      move_threshold:
        name: G5 move threshold
        internal: True
      still_threshold:
        name: G5 still threshold
        internal: True
    g6:
      move_threshold:
        name: G6 move threshold
        internal: True
      still_threshold:
        name: G6 still threshold
        internal: True
    g7:
      move_threshold:
        name: G7 move threshold
        internal: True
      still_threshold:
        name: G7 still threshold
        internal: True
    g8:
      move_threshold:
        name: G8 move threshold
        internal: True
      still_threshold:
        name: G8 still threshold
        internal: True

  - platform: template # Lux auto on 
    name: "Light threshold (lux)"
    id: start_lux
    internal: false
    max_value: 10.0
    min_value: 0.1
    initial_value: 1.0
    step: 0.1
    optimistic: true
    mode: slider
    restore_value: true


button:
  - platform: ld2410
    restart:
      name: "Restart sensor"
  - platform: restart
    name: "Restart device"

text_sensor:
  - platform: ld2410
    version:
      name: "Firmware sensor version"
                                                                                                                                                                                                               
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID
